
                    <a class="item" href="https://embedthis.com/">Embedthis</a>
                    <a class="item" href="https://embedthis.com/esp/">ESP Site</a>
                    <span class="desktop-only">
                        <a class="item" href="https://embedthis.com/blog/categories/ESP/">ESP News</a>
                        <a class="item" href="https://github.com/embedthis/esp">Repository</a>
                        <a class="item" href="https://embedthis.com/blog/">Blog</a>
                        <a class="item" href="https://twitter.com/embedthat">Twitter</a>
                    </span>
